function dydt=NetfluxODE(t,y,params) 
% NetfluxODE.m 
% Automatically generated by Netflux on 21-Feb-2024
 
% Assign names for parameters 
[rpar,tau,ymax,speciesNames]=params{:}; 
Akt = 1; 
AP1 = 2; 
apoptosis = 3; 
ASK1 = 4; 
Bad = 5; 
Bax = 6; 
Bcl2 = 7; 
Bcl2t = 8; 
Bim = 9; 
CAD = 10; 
cas3 = 11; 
cas9 = 12; 
cellDeath = 13; 
CREB = 14; 
cytc = 15; 
DNAfrag = 16; 
EGF = 17; 
EGFR = 18; 
ERBB = 19; 
ERK12 = 20; 
FGF = 21; 
FGFR = 22; 
FLT3 = 23; 
FLT3L = 24; 
iCAD = 25; 
iCADt = 26; 
IGF1 = 27; 
IGF1R = 28; 
IkB = 29; 
IKK = 30; 
JAK = 31; 
JNK = 32; 
KIT = 33; 
MEK12 = 34; 
MEK36 = 35; 
MEK47 = 36; 
MOMP = 37; 
NFkB = 38; 
NOX = 39; 
Noxa = 40; 
NRG1 = 41; 
p38 = 42; 
p53 = 43; 
PARP = 44; 
PDGF = 45; 
PDGFR = 46; 
PDK1 = 47; 
PI3K = 48; 
PUMA = 49; 
Raf = 50; 
Ras = 51; 
ROS = 52; 
RSK = 53; 
SCF = 54; 
Smac = 55; 
STAT = 56; 
Trx = 57; 
Trxt = 58; 
VEGF = 59; 
VEGFR = 60; 
xIAP = 61; 
xIAPt = 62; 
LRP1 = 63; 
LRP1ag = 64; 
dydt = zeros(64,1); 
dydt(Akt) = (act(y(PDK1),rpar(:,94))*ymax(Akt) - y(Akt))/tau(Akt); 
dydt(AP1) = (act(y(JNK),rpar(:,74))*ymax(AP1) - y(AP1))/tau(AP1); 
dydt(apoptosis) = (act(y(DNAfrag),rpar(:,55))*ymax(apoptosis) - y(apoptosis))/tau(apoptosis); 
dydt(ASK1) = (OR(inhib(y(Trx),rpar(:,43)),AND(rpar(:,97),inhib(y(Akt),rpar(:,97)),act(y(ROS),rpar(:,97))))*ymax(ASK1) - y(ASK1))/tau(ASK1); 
dydt(Bad) = (OR(inhib(y(Akt),rpar(:,19)),act(y(JNK),rpar(:,75)))*ymax(Bad) - y(Bad))/tau(Bad); 
dydt(Bax) = (OR(AND(rpar(:,18),inhib(y(Akt),rpar(:,18)),act(y(ROS),rpar(:,18))),OR(inhib(y(Bcl2),rpar(:,22)),act(y(p53),rpar(:,88))))*ymax(Bax) - y(Bax))/tau(Bax); 
dydt(Bcl2) = (OR(AND(rpar(:,21),inhib(y(Bad),rpar(:,21)),act(y(Bcl2t),rpar(:,21))),OR(AND(rpar(:,23),act(y(Bcl2t),rpar(:,23)),inhib(y(Bim),rpar(:,23))),OR(AND(rpar(:,30),act(y(Bcl2t),rpar(:,30)),inhib(y(JNK),rpar(:,30))),OR(AND(rpar(:,32),act(y(Bcl2t),rpar(:,32)),inhib(y(Noxa),rpar(:,32))),AND(rpar(:,36),act(y(Bcl2t),rpar(:,36)),inhib(y(PUMA),rpar(:,36)))))))*ymax(Bcl2) - y(Bcl2))/tau(Bcl2); 
dydt(Bcl2t) = (OR(rpar(1,5),OR(act(y(CREB),rpar(:,53)),OR(act(y(NFkB),rpar(:,85)),act(y(STAT),rpar(:,99)))))*ymax(Bcl2t) - y(Bcl2t))/tau(Bcl2t); 
dydt(Bim) = (OR(inhib(y(Akt),rpar(:,20)),OR(act(y(JNK),rpar(:,76)),act(y(p38),rpar(:,87))))*ymax(Bim) - y(Bim))/tau(Bim); 
dydt(CAD) = (inhib(y(iCAD),rpar(:,27))*ymax(CAD) - y(CAD))/tau(CAD); 
dydt(cas3) = (OR(inhib(y(xIAP),rpar(:,44)),act(y(cas9),rpar(:,52)))*ymax(cas3) - y(cas3))/tau(cas3); 
dydt(cas9) = (OR(inhib(y(xIAP),rpar(:,45)),act(y(cytc),rpar(:,54)))*ymax(cas9) - y(cas9))/tau(cas9); 
dydt(cellDeath) = (act(y(apoptosis),rpar(:,48))*ymax(cellDeath) - y(cellDeath))/tau(cellDeath); 
dydt(CREB) = (act(y(RSK),rpar(:,98))*ymax(CREB) - y(CREB))/tau(CREB); 
dydt(cytc) = (act(y(MOMP),rpar(:,83))*ymax(cytc) - y(cytc))/tau(cytc); 
dydt(DNAfrag) = (AND(rpar(:,33),act(y(CAD),rpar(:,33)),inhib(y(PARP),rpar(:,33)))*ymax(DNAfrag) - y(DNAfrag))/tau(DNAfrag); 
dydt(EGF) = (rpar(1,6)*ymax(EGF) - y(EGF))/tau(EGF); 
dydt(EGFR) = (act(y(EGF),rpar(:,26))*ymax(EGFR) - y(EGFR))/tau(EGFR); 
dydt(ERBB) = (act(y(NRG1),rpar(:,42))*ymax(ERBB) - y(ERBB))/tau(ERBB); 
dydt(ERK12) = (act(y(MEK12),rpar(:,80))*ymax(ERK12) - y(ERK12))/tau(ERK12); 
dydt(FGF) = (rpar(1,7)*ymax(FGF) - y(FGF))/tau(FGF); 
dydt(FGFR) = (act(y(FGF),rpar(:,35))*ymax(FGFR) - y(FGFR))/tau(FGFR); 
dydt(FLT3) = (act(y(FLT3L),rpar(:,34))*ymax(FLT3) - y(FLT3))/tau(FLT3); 
dydt(FLT3L) = (rpar(1,8)*ymax(FLT3L) - y(FLT3L))/tau(FLT3L); 
dydt(iCAD) = (AND(rpar(:,25),inhib(y(cas3),rpar(:,25)),act(y(iCADt),rpar(:,25)))*ymax(iCAD) - y(iCAD))/tau(iCAD); 
dydt(iCADt) = (rpar(1,9)*ymax(iCADt) - y(iCADt))/tau(iCADt); 
dydt(IGF1) = (rpar(1,10)*ymax(IGF1) - y(IGF1))/tau(IGF1); 
dydt(IGF1R) = (act(y(IGF1),rpar(:,69))*ymax(IGF1R) - y(IGF1R))/tau(IGF1R); 
dydt(IkB) = (inhib(y(IKK),rpar(:,29))*ymax(IkB) - y(IkB))/tau(IkB); 
dydt(IKK) = (act(y(Akt),rpar(:,46))*ymax(IKK) - y(IKK))/tau(IKK); 
dydt(JAK) = (OR(act(y(EGFR),rpar(:,56)),OR(act(y(ERBB),rpar(:,59)),OR(act(y(FGFR),rpar(:,63)),OR(act(y(FLT3),rpar(:,66)),OR(act(y(IGF1R),rpar(:,70)),OR(act(y(KIT),rpar(:,77)),OR(act(y(PDGFR),rpar(:,91)),act(y(VEGFR),rpar(:,100)))))))))*ymax(JAK) - y(JAK))/tau(JAK); 
dydt(JNK) = (act(y(MEK47),rpar(:,82))*ymax(JNK) - y(JNK))/tau(JNK); 
dydt(KIT) = (act(y(SCF),rpar(:,31))*ymax(KIT) - y(KIT))/tau(KIT); 
dydt(MEK12) = (act(y(Raf),rpar(:,96))*ymax(MEK12) - y(MEK12))/tau(MEK12); 
dydt(MEK36) = (act(y(ASK1),rpar(:,49))*ymax(MEK36) - y(MEK36))/tau(MEK36); 
dydt(MEK47) = (act(y(ASK1),rpar(:,50))*ymax(MEK47) - y(MEK47))/tau(MEK47); 
dydt(MOMP) = (act(y(Bax),rpar(:,51))*ymax(MOMP) - y(MOMP))/tau(MOMP); 
dydt(NFkB) = (inhib(y(IkB),rpar(:,28))*ymax(NFkB) - y(NFkB))/tau(NFkB); 
dydt(NOX) = (0*ymax(NOX) - y(NOX))/tau(NOX); 
dydt(Noxa) = (act(y(p53),rpar(:,89))*ymax(Noxa) - y(Noxa))/tau(Noxa); 
dydt(NRG1) = (rpar(1,11)*ymax(NRG1) - y(NRG1))/tau(NRG1); 
dydt(p38) = (act(y(MEK36),rpar(:,81))*ymax(p38) - y(p38))/tau(p38); 
dydt(p53) = (act(y(AP1),rpar(:,47))*ymax(p53) - y(p53))/tau(p53); 
dydt(PARP) = (inhib(y(cas3),rpar(:,24))*ymax(PARP) - y(PARP))/tau(PARP); 
dydt(PDGF) = (rpar(1,12)*ymax(PDGF) - y(PDGF))/tau(PDGF); 
dydt(PDGFR) = (act(y(PDGF),rpar(:,39))*ymax(PDGFR) - y(PDGFR))/tau(PDGFR); 
dydt(PDK1) = (act(y(PI3K),rpar(:,95))*ymax(PDK1) - y(PDK1))/tau(PDK1); 
dydt(PI3K) = (OR(act(y(LRP1),rpar(:,3)),OR(act(y(EGFR),rpar(:,57)),OR(act(y(ERBB),rpar(:,60)),OR(act(y(FGFR),rpar(:,64)),OR(act(y(FLT3),rpar(:,67)),OR(act(y(IGF1R),rpar(:,71)),OR(act(y(KIT),rpar(:,78)),OR(act(y(PDGFR),rpar(:,92)),act(y(VEGFR),rpar(:,101))))))))))*ymax(PI3K) - y(PI3K))/tau(PI3K); 
dydt(PUMA) = (act(y(p53),rpar(:,90))*ymax(PUMA) - y(PUMA))/tau(PUMA); 
dydt(Raf) = (act(y(Ras),rpar(:,41))*ymax(Raf) - y(Raf))/tau(Raf); 
dydt(Ras) = (OR(act(y(LRP1),rpar(:,4)),OR(act(y(EGFR),rpar(:,58)),OR(act(y(ERBB),rpar(:,61)),OR(act(y(FGFR),rpar(:,65)),OR(act(y(FLT3),rpar(:,68)),OR(act(y(IGF1R),rpar(:,72)),OR(act(y(KIT),rpar(:,79)),OR(act(y(PDGFR),rpar(:,93)),act(y(VEGFR),rpar(:,102))))))))))*ymax(Ras) - y(Ras))/tau(Ras); 
dydt(ROS) = (OR(rpar(1,13),act(y(NOX),rpar(:,86)))*ymax(ROS) - y(ROS))/tau(ROS); 
dydt(RSK) = (act(y(ERK12),rpar(:,62))*ymax(RSK) - y(RSK))/tau(RSK); 
dydt(SCF) = (rpar(1,14)*ymax(SCF) - y(SCF))/tau(SCF); 
dydt(Smac) = (act(y(MOMP),rpar(:,84))*ymax(Smac) - y(Smac))/tau(Smac); 
dydt(STAT) = (act(y(JAK),rpar(:,73))*ymax(STAT) - y(STAT))/tau(STAT); 
dydt(Trx) = (AND(rpar(:,37),inhib(y(ROS),rpar(:,37)),act(y(Trxt),rpar(:,37)))*ymax(Trx) - y(Trx))/tau(Trx); 
dydt(Trxt) = (rpar(1,15)*ymax(Trxt) - y(Trxt))/tau(Trxt); 
dydt(VEGF) = (rpar(1,16)*ymax(VEGF) - y(VEGF))/tau(VEGF); 
dydt(VEGFR) = (act(y(VEGF),rpar(:,40))*ymax(VEGFR) - y(VEGFR))/tau(VEGFR); 
dydt(xIAP) = (AND(rpar(:,38),inhib(y(Smac),rpar(:,38)),act(y(xIAPt),rpar(:,38)))*ymax(xIAP) - y(xIAP))/tau(xIAP); 
dydt(xIAPt) = (rpar(1,17)*ymax(xIAPt) - y(xIAPt))/tau(xIAPt); 
dydt(LRP1) = (act(y(LRP1ag),rpar(:,2))*ymax(LRP1) - y(LRP1))/tau(LRP1); 
dydt(LRP1ag) = (rpar(1,1)*ymax(LRP1ag) - y(LRP1ag))/tau(LRP1ag); 

% utility functions 
function fact = act(x,rpar) 
% hill activation function with parameters w (weight), n (Hill coeff), EC50 
    w = rpar(1); 
    n = rpar(2); 
    EC50 = rpar(3); 
    beta = (EC50.^n - 1)./(2*EC50.^n - 1); 
    K = (beta - 1).^(1./n); 
    fact = w.*(beta.*x.^n)./(K.^n + x.^n); 
    if fact>w,                 % cap fact(x)<= 1 
        fact = w; 
    end
 
function finhib = inhib(x,rpar) 
% inverse hill function with parameters w (weight), n (Hill coeff), EC50 
    finhib = rpar(1) - act(x,rpar);
 
function z = OR(x,y) 
% OR logic gate 
    z = x + y - x*y;
 
function z = AND(rpar,varargin) 
% AND logic gate, multiplying all of the reactants together 
    w = rpar(1); 
    if w == 0, 
        z = 0; 
    else 
        v = cell2mat(varargin); 
        z = prod(v)/w^(nargin-2);  
    end 
