function dydt=ODEfun(t,y,params) 
% Assign names for parameters 
[rpar,tau,ymax,speciesNames]=params{:}; 
Akt = 1; 
AP1 = 2; 
apoptosis = 3; 
ASK1 = 4; 
Bad = 5; 
Bax = 6; 
Bcl2 = 7; 
Bcl2t = 8; 
Bim = 9; 
CAD = 10; 
cas3 = 11; 
cas9 = 12; 
cellDeath = 13; 
CREB = 14; 
cytc = 15; 
DNAfrag = 16; 
EGF = 17; 
EGFR = 18; 
ERBB = 19; 
ERK12 = 20; 
ERL = 21; 
FGF = 22; 
FGFR = 23; 
FLT3 = 24; 
FLT3L = 25; 
GEF = 26; 
iCAD = 27; 
iCADt = 28; 
IGF1 = 29; 
IGF1R = 30; 
IkB = 31; 
IKK = 32; 
JAK = 33; 
JNK = 34; 
KIT = 35; 
MEK12 = 36; 
MEK36 = 37; 
MEK47 = 38; 
MOMP = 39; 
NFkB = 40; 
NIL = 41; 
NOX = 42; 
Noxa = 43; 
NRG1 = 44; 
p38 = 45; 
p53 = 46; 
PARP = 47; 
PDGF = 48; 
PDGFR = 49; 
PDK1 = 50; 
PI3K = 51; 
PON = 52; 
PUMA = 53; 
Raf = 54; 
Ras = 55; 
ROS = 56; 
RSK = 57; 
SCF = 58; 
Smac = 59; 
SOR = 60; 
STAT = 61; 
SUN = 62; 
TRAZ = 63; 
Trx = 64; 
Trxt = 65; 
VEGF = 66; 
VEGFR = 67; 
xIAP = 68; 
xIAPt = 69; 
dydt = zeros(69,1); 
dydt(Akt) = (act(y(PDK1),rpar(:,96))*ymax(Akt) - y(Akt))/tau(Akt); 
dydt(AP1) = (act(y(JNK),rpar(:,77))*ymax(AP1) - y(AP1))/tau(AP1); 
dydt(apoptosis) = (act(y(DNAfrag),rpar(:,56))*ymax(apoptosis) - y(apoptosis))/tau(apoptosis); 
dydt(ASK1) = (OR(inhib(y(Trx),rpar(:,43)),AND(rpar(:,100),inhib(y(Akt),rpar(:,100)),act(y(ROS),rpar(:,100))))*ymax(ASK1) - y(ASK1))/tau(ASK1); 
dydt(Bad) = (inhib(y(Akt),rpar(:,23))*ymax(Bad) - y(Bad))/tau(Bad); 
dydt(Bax) = (OR(AND(rpar(:,22),inhib(y(Akt),rpar(:,22)),act(y(ROS),rpar(:,22))),OR(inhib(y(Bcl2),rpar(:,26)),act(y(p53),rpar(:,91))))*ymax(Bax) - y(Bax))/tau(Bax); 
dydt(Bcl2) = (OR(AND(rpar(:,25),inhib(y(Bad),rpar(:,25)),act(y(Bcl2t),rpar(:,25)),inhib(y(Bim),rpar(:,25)),inhib(y(Noxa),rpar(:,25)),inhib(y(PUMA),rpar(:,25))),act(y(Bcl2t),rpar(:,52)))*ymax(Bcl2) - y(Bcl2))/tau(Bcl2); 
dydt(Bcl2t) = (OR(rpar(1,8),OR(act(y(CREB),rpar(:,54)),OR(act(y(NFkB),rpar(:,87)),act(y(STAT),rpar(:,104)))))*ymax(Bcl2t) - y(Bcl2t))/tau(Bcl2t); 
dydt(Bim) = (OR(inhib(y(Akt),rpar(:,24)),OR(act(y(JNK),rpar(:,78)),act(y(p38),rpar(:,90))))*ymax(Bim) - y(Bim))/tau(Bim); 
dydt(CAD) = (inhib(y(iCAD),rpar(:,30))*ymax(CAD) - y(CAD))/tau(CAD); 
dydt(cas3) = (OR(inhib(y(xIAP),rpar(:,44)),act(y(cas9),rpar(:,53)))*ymax(cas3) - y(cas3))/tau(cas3); 
dydt(cas9) = (OR(inhib(y(xIAP),rpar(:,45)),act(y(cytc),rpar(:,55)))*ymax(cas9) - y(cas9))/tau(cas9); 
dydt(cellDeath) = (act(y(apoptosis),rpar(:,48))*ymax(cellDeath) - y(cellDeath))/tau(cellDeath); 
dydt(CREB) = (act(y(RSK),rpar(:,102))*ymax(CREB) - y(CREB))/tau(CREB); 
dydt(cytc) = (act(y(MOMP),rpar(:,85))*ymax(cytc) - y(cytc))/tau(cytc); 
dydt(DNAfrag) = (AND(rpar(:,34),act(y(CAD),rpar(:,34)),inhib(y(PARP),rpar(:,34)))*ymax(DNAfrag) - y(DNAfrag))/tau(DNAfrag); 
dydt(EGF) = (rpar(1,9)*ymax(EGF) - y(EGF))/tau(EGF); 
dydt(EGFR) = (AND(rpar(:,29),act(y(EGF),rpar(:,29)),inhib(y(ERL),rpar(:,29)),inhib(y(GEF),rpar(:,29)))*ymax(EGFR) - y(EGFR))/tau(EGFR); 
dydt(ERBB) = (AND(rpar(:,42),act(y(NRG1),rpar(:,42)),inhib(y(TRAZ),rpar(:,42)))*ymax(ERBB) - y(ERBB))/tau(ERBB); 
dydt(ERK12) = (act(y(MEK12),rpar(:,82))*ymax(ERK12) - y(ERK12))/tau(ERK12); 
dydt(ERL) = (rpar(1,1)*ymax(ERL) - y(ERL))/tau(ERL); 
dydt(FGF) = (rpar(1,10)*ymax(FGF) - y(FGF))/tau(FGF); 
dydt(FGFR) = (AND(rpar(:,36),act(y(FGF),rpar(:,36)),inhib(y(PON),rpar(:,36)),inhib(y(SOR),rpar(:,36)))*ymax(FGFR) - y(FGFR))/tau(FGFR); 
dydt(FLT3) = (AND(rpar(:,35),act(y(FLT3L),rpar(:,35)),inhib(y(PON),rpar(:,35)),inhib(y(SOR),rpar(:,35)),inhib(y(SUN),rpar(:,35)))*ymax(FLT3) - y(FLT3))/tau(FLT3); 
dydt(FLT3L) = (rpar(1,11)*ymax(FLT3L) - y(FLT3L))/tau(FLT3L); 
dydt(GEF) = (rpar(1,2)*ymax(GEF) - y(GEF))/tau(GEF); 
dydt(iCAD) = (AND(rpar(:,28),inhib(y(cas3),rpar(:,28)),act(y(iCADt),rpar(:,28)))*ymax(iCAD) - y(iCAD))/tau(iCAD); 
dydt(iCADt) = (rpar(1,12)*ymax(iCADt) - y(iCADt))/tau(iCADt); 
dydt(IGF1) = (rpar(1,13)*ymax(IGF1) - y(IGF1))/tau(IGF1); 
dydt(IGF1R) = (act(y(IGF1),rpar(:,72))*ymax(IGF1R) - y(IGF1R))/tau(IGF1R); 
dydt(IkB) = (OR(rpar(1,14),inhib(y(IKK),rpar(:,32)))*ymax(IkB) - y(IkB))/tau(IkB); 
dydt(IKK) = (act(y(ROS),rpar(:,101))*ymax(IKK) - y(IKK))/tau(IKK); 
dydt(JAK) = (OR(act(y(EGFR),rpar(:,57)),OR(act(y(ERBB),rpar(:,60)),OR(act(y(FGFR),rpar(:,65)),OR(act(y(FLT3),rpar(:,68)),OR(act(y(IGF1R),rpar(:,73)),OR(act(y(KIT),rpar(:,79)),act(y(PDGFR),rpar(:,94))))))))*ymax(JAK) - y(JAK))/tau(JAK); 
dydt(JNK) = (act(y(MEK47),rpar(:,84))*ymax(JNK) - y(JNK))/tau(JNK); 
dydt(KIT) = (AND(rpar(:,33),inhib(y(NIL),rpar(:,33)),inhib(y(PON),rpar(:,33)),act(y(SCF),rpar(:,33)),inhib(y(SOR),rpar(:,33)),inhib(y(SUN),rpar(:,33)))*ymax(KIT) - y(KIT))/tau(KIT); 
dydt(MEK12) = (act(y(Raf),rpar(:,99))*ymax(MEK12) - y(MEK12))/tau(MEK12); 
dydt(MEK36) = (act(y(ASK1),rpar(:,49))*ymax(MEK36) - y(MEK36))/tau(MEK36); 
dydt(MEK47) = (act(y(ASK1),rpar(:,50))*ymax(MEK47) - y(MEK47))/tau(MEK47); 
dydt(MOMP) = (act(y(Bax),rpar(:,51))*ymax(MOMP) - y(MOMP))/tau(MOMP); 
dydt(NFkB) = (inhib(y(IkB),rpar(:,31))*ymax(NFkB) - y(NFkB))/tau(NFkB); 
dydt(NIL) = (rpar(1,3)*ymax(NIL) - y(NIL))/tau(NIL); 
dydt(NOX) = (OR(act(y(ERL),rpar(:,64)),act(y(NIL),rpar(:,88)))*ymax(NOX) - y(NOX))/tau(NOX); 
dydt(Noxa) = (act(y(p53),rpar(:,92))*ymax(Noxa) - y(Noxa))/tau(Noxa); 
dydt(NRG1) = (rpar(1,15)*ymax(NRG1) - y(NRG1))/tau(NRG1); 
dydt(p38) = (act(y(MEK36),rpar(:,83))*ymax(p38) - y(p38))/tau(p38); 
dydt(p53) = (act(y(AP1),rpar(:,47))*ymax(p53) - y(p53))/tau(p53); 
dydt(PARP) = (inhib(y(cas3),rpar(:,27))*ymax(PARP) - y(PARP))/tau(PARP); 
dydt(PDGF) = (rpar(1,16)*ymax(PDGF) - y(PDGF))/tau(PDGF); 
dydt(PDGFR) = (AND(rpar(:,39),act(y(PDGF),rpar(:,39)),inhib(y(SOR),rpar(:,39)),inhib(y(SUN),rpar(:,39)))*ymax(PDGFR) - y(PDGFR))/tau(PDGFR); 
dydt(PDK1) = (act(y(PI3K),rpar(:,97))*ymax(PDK1) - y(PDK1))/tau(PDK1); 
dydt(PI3K) = (OR(act(y(EGFR),rpar(:,58)),OR(act(y(ERBB),rpar(:,61)),OR(act(y(FGFR),rpar(:,66)),OR(act(y(FLT3),rpar(:,69)),OR(act(y(IGF1R),rpar(:,74)),OR(act(y(KIT),rpar(:,80)),OR(act(y(PDGFR),rpar(:,95)),act(y(VEGFR),rpar(:,107)))))))))*ymax(PI3K) - y(PI3K))/tau(PI3K); 
dydt(PON) = (rpar(1,4)*ymax(PON) - y(PON))/tau(PON); 
dydt(PUMA) = (act(y(p53),rpar(:,93))*ymax(PUMA) - y(PUMA))/tau(PUMA); 
dydt(Raf) = (AND(rpar(:,41),act(y(Ras),rpar(:,41)),inhib(y(SOR),rpar(:,41)))*ymax(Raf) - y(Raf))/tau(Raf); 
dydt(Ras) = (OR(act(y(EGFR),rpar(:,59)),OR(act(y(ERBB),rpar(:,62)),OR(act(y(FGFR),rpar(:,67)),OR(act(y(FLT3),rpar(:,70)),OR(act(y(IGF1R),rpar(:,75)),OR(act(y(KIT),rpar(:,81)),act(y(VEGFR),rpar(:,108))))))))*ymax(Ras) - y(Ras))/tau(Ras); 
dydt(ROS) = (OR(rpar(1,17),OR(act(y(GEF),rpar(:,71)),OR(act(y(NOX),rpar(:,89)),OR(act(y(PON),rpar(:,98)),OR(act(y(SOR),rpar(:,103)),OR(act(y(SUN),rpar(:,105)),act(y(TRAZ),rpar(:,106))))))))*ymax(ROS) - y(ROS))/tau(ROS); 
dydt(RSK) = (act(y(ERK12),rpar(:,63))*ymax(RSK) - y(RSK))/tau(RSK); 
dydt(SCF) = (rpar(1,18)*ymax(SCF) - y(SCF))/tau(SCF); 
dydt(Smac) = (act(y(MOMP),rpar(:,86))*ymax(Smac) - y(Smac))/tau(Smac); 
dydt(SOR) = (rpar(1,5)*ymax(SOR) - y(SOR))/tau(SOR); 
dydt(STAT) = (act(y(JAK),rpar(:,76))*ymax(STAT) - y(STAT))/tau(STAT); 
dydt(SUN) = (rpar(1,6)*ymax(SUN) - y(SUN))/tau(SUN); 
dydt(TRAZ) = (rpar(1,7)*ymax(TRAZ) - y(TRAZ))/tau(TRAZ); 
dydt(Trx) = (AND(rpar(:,37),inhib(y(ROS),rpar(:,37)),act(y(Trxt),rpar(:,37)))*ymax(Trx) - y(Trx))/tau(Trx); 
dydt(Trxt) = (rpar(1,19)*ymax(Trxt) - y(Trxt))/tau(Trxt); 
dydt(VEGF) = (rpar(1,20)*ymax(VEGF) - y(VEGF))/tau(VEGF); 
dydt(VEGFR) = (AND(rpar(:,40),inhib(y(SOR),rpar(:,40)),inhib(y(SUN),rpar(:,40)),act(y(VEGF),rpar(:,40)))*ymax(VEGFR) - y(VEGFR))/tau(VEGFR); 
dydt(xIAP) = (OR(AND(rpar(:,38),inhib(y(Smac),rpar(:,38)),act(y(xIAPt),rpar(:,38))),act(y(Akt),rpar(:,46)))*ymax(xIAP) - y(xIAP))/tau(xIAP); 
dydt(xIAPt) = (rpar(1,21)*ymax(xIAPt) - y(xIAPt))/tau(xIAPt); 

% utility functions 
function fact = act(x,rpar) 
% hill activation function with parameters w (weight), n (Hill coeff), EC50 
    w = rpar(1); 
    n = rpar(2); 
    EC50 = rpar(3); 
    beta = (EC50.^n - 1)./(2*EC50.^n - 1); 
    K = (beta - 1).^(1./n); 
    fact = w.*(beta.*x.^n)./(K.^n + x.^n); 
    if fact>w,                 % cap fact(x)<= 1 
        fact = w; 
    end
 
function finhib = inhib(x,rpar) 
% inverse hill function with parameters w (weight), n (Hill coeff), EC50 
    finhib = 1 - act(x,rpar);
 
function z = OR(x,y) 
% OR logic gate 
    z = 1-(1-x)*(1-y);
 
function z = AND(rpar,varargin) 
% AND logic gate, multiplying all of the reactants together 
    w = rpar(1); 
        v = real(cell2mat(varargin)); 
        h = (sum(v)/(nargin-1))^(nargin-2); 
    if w == 0 
        z = 0; 
    elseif h == 0 
        z = 0; 
    else 
        z = prod(v)/h; 
    end 
