# TKI-apoptosis.py 
# Automatically generated by Netflux on 10-Jan-2024 
import numpy as np 
def ODEfunc(t,y,tau,ymax,w,n,EC50): 
	Akt = 0 
	AP1 = 1 
	apoptosis = 2 
	ASK1 = 3 
	Bad = 4 
	Bax = 5 
	Bcl2 = 6 
	Bcl2t = 7 
	Bim = 8 
	CAD = 9 
	cas3 = 10 
	cas9 = 11 
	cellDeath = 12 
	CREB = 13 
	cytc = 14 
	DNAfrag = 15 
	EGF = 16 
	EGFR = 17 
	ERBB = 18 
	ERK12 = 19 
	ERL = 20 
	FGF = 21 
	FGFR = 22 
	FLT3 = 23 
	FLT3L = 24 
	GEF = 25 
	iCAD = 26 
	iCADt = 27 
	IGF1 = 28 
	IGF1R = 29 
	IkB = 30 
	IKK = 31 
	JAK = 32 
	JNK = 33 
	KIT = 34 
	MEK12 = 35 
	MEK36 = 36 
	MEK47 = 37 
	MOMP = 38 
	NFkB = 39 
	NIL = 40 
	NOX = 41 
	Noxa = 42 
	NRG1 = 43 
	p38 = 44 
	p53 = 45 
	PARP = 46 
	PDGF = 47 
	PDGFR = 48 
	PDK1 = 49 
	PI3K = 50 
	PON = 51 
	PUMA = 52 
	Raf = 53 
	Ras = 54 
	ROS = 55 
	RSK = 56 
	SCF = 57 
	Smac = 58 
	SOR = 59 
	STAT = 60 
	SUN = 61 
	TRAZ = 62 
	Trx = 63 
	Trxt = 64 
	VEGF = 65 
	VEGFR = 66 
	xIAP = 67 
	xIAPt = 68 
	dydt = np.zeros(69) 
	dydt[Akt] = (act(y[PDK1],w[99],n[99],EC50[99])*ymax[Akt] - y[Akt])/tau[Akt] 
	dydt[AP1] = (act(y[JNK],w[78],n[78],EC50[78])*ymax[AP1] - y[AP1])/tau[AP1] 
	dydt[apoptosis] = (act(y[DNAfrag],w[57],n[57],EC50[57])*ymax[apoptosis] - y[apoptosis])/tau[apoptosis] 
	dydt[ASK1] = (OR(inhib(y[Trx],w[45],n[45],EC50[45]),AND(w[103],[inhib(y[Akt],w[103],n[103],EC50[103]),act(y[ROS],w[103],n[103],EC50[103])]))*ymax[ASK1] - y[ASK1])/tau[ASK1] 
	dydt[Bad] = (OR(inhib(y[Akt],w[21],n[21],EC50[21]),act(y[JNK],w[79],n[79],EC50[79]))*ymax[Bad] - y[Bad])/tau[Bad] 
	dydt[Bax] = (OR(AND(w[20],[inhib(y[Akt],w[20],n[20],EC50[20]),act(y[ROS],w[20],n[20],EC50[20])]),OR(inhib(y[Bcl2],w[24],n[24],EC50[24]),act(y[p53],w[93],n[93],EC50[93])))*ymax[Bax] - y[Bax])/tau[Bax] 
	dydt[Bcl2] = (OR(AND(w[23],[inhib(y[Bad],w[23],n[23],EC50[23]),act(y[Bcl2t],w[23],n[23],EC50[23])]),OR(AND(w[25],[act(y[Bcl2t],w[25],n[25],EC50[25]),inhib(y[Bim],w[25],n[25],EC50[25])]),OR(AND(w[32],[act(y[Bcl2t],w[32],n[32],EC50[32]),inhib(y[JNK],w[32],n[32],EC50[32])]),OR(AND(w[34],[act(y[Bcl2t],w[34],n[34],EC50[34]),inhib(y[Noxa],w[34],n[34],EC50[34])]),AND(w[38],[act(y[Bcl2t],w[38],n[38],EC50[38]),inhib(y[PUMA],w[38],n[38],EC50[38])])))))*ymax[Bcl2] - y[Bcl2])/tau[Bcl2] 
	dydt[Bcl2t] = (OR(w[7],OR(act(y[CREB],w[55],n[55],EC50[55]),OR(act(y[NFkB],w[89],n[89],EC50[89]),act(y[STAT],w[106],n[106],EC50[106]))))*ymax[Bcl2t] - y[Bcl2t])/tau[Bcl2t] 
	dydt[Bim] = (OR(inhib(y[Akt],w[22],n[22],EC50[22]),OR(act(y[JNK],w[80],n[80],EC50[80]),act(y[p38],w[92],n[92],EC50[92])))*ymax[Bim] - y[Bim])/tau[Bim] 
	dydt[CAD] = (inhib(y[iCAD],w[29],n[29],EC50[29])*ymax[CAD] - y[CAD])/tau[CAD] 
	dydt[cas3] = (OR(inhib(y[xIAP],w[46],n[46],EC50[46]),act(y[cas9],w[54],n[54],EC50[54]))*ymax[cas3] - y[cas3])/tau[cas3] 
	dydt[cas9] = (OR(inhib(y[xIAP],w[47],n[47],EC50[47]),act(y[cytc],w[56],n[56],EC50[56]))*ymax[cas9] - y[cas9])/tau[cas9] 
	dydt[cellDeath] = (act(y[apoptosis],w[50],n[50],EC50[50])*ymax[cellDeath] - y[cellDeath])/tau[cellDeath] 
	dydt[CREB] = (act(y[RSK],w[104],n[104],EC50[104])*ymax[CREB] - y[CREB])/tau[CREB] 
	dydt[cytc] = (act(y[MOMP],w[87],n[87],EC50[87])*ymax[cytc] - y[cytc])/tau[cytc] 
	dydt[DNAfrag] = (AND(w[35],[act(y[CAD],w[35],n[35],EC50[35]),inhib(y[PARP],w[35],n[35],EC50[35])])*ymax[DNAfrag] - y[DNAfrag])/tau[DNAfrag] 
	dydt[EGF] = (w[8]*ymax[EGF] - y[EGF])/tau[EGF] 
	dydt[EGFR] = (AND(w[28],[act(y[EGF],w[28],n[28],EC50[28]),inhib(y[ERL],w[28],n[28],EC50[28]),inhib(y[GEF],w[28],n[28],EC50[28])])*ymax[EGFR] - y[EGFR])/tau[EGFR] 
	dydt[ERBB] = (AND(w[44],[act(y[NRG1],w[44],n[44],EC50[44]),inhib(y[TRAZ],w[44],n[44],EC50[44])])*ymax[ERBB] - y[ERBB])/tau[ERBB] 
	dydt[ERK12] = (act(y[MEK12],w[84],n[84],EC50[84])*ymax[ERK12] - y[ERK12])/tau[ERK12] 
	dydt[ERL] = (w[0]*ymax[ERL] - y[ERL])/tau[ERL] 
	dydt[FGF] = (w[9]*ymax[FGF] - y[FGF])/tau[FGF] 
	dydt[FGFR] = (AND(w[37],[act(y[FGF],w[37],n[37],EC50[37]),inhib(y[PON],w[37],n[37],EC50[37]),inhib(y[SOR],w[37],n[37],EC50[37])])*ymax[FGFR] - y[FGFR])/tau[FGFR] 
	dydt[FLT3] = (AND(w[36],[act(y[FLT3L],w[36],n[36],EC50[36]),inhib(y[PON],w[36],n[36],EC50[36]),inhib(y[SOR],w[36],n[36],EC50[36]),inhib(y[SUN],w[36],n[36],EC50[36])])*ymax[FLT3] - y[FLT3])/tau[FLT3] 
	dydt[FLT3L] = (w[10]*ymax[FLT3L] - y[FLT3L])/tau[FLT3L] 
	dydt[GEF] = (w[1]*ymax[GEF] - y[GEF])/tau[GEF] 
	dydt[iCAD] = (AND(w[27],[inhib(y[cas3],w[27],n[27],EC50[27]),act(y[iCADt],w[27],n[27],EC50[27])])*ymax[iCAD] - y[iCAD])/tau[iCAD] 
	dydt[iCADt] = (w[11]*ymax[iCADt] - y[iCADt])/tau[iCADt] 
	dydt[IGF1] = (w[12]*ymax[IGF1] - y[IGF1])/tau[IGF1] 
	dydt[IGF1R] = (act(y[IGF1],w[73],n[73],EC50[73])*ymax[IGF1R] - y[IGF1R])/tau[IGF1R] 
	dydt[IkB] = (inhib(y[IKK],w[31],n[31],EC50[31])*ymax[IkB] - y[IkB])/tau[IkB] 
	dydt[IKK] = (act(y[Akt],w[48],n[48],EC50[48])*ymax[IKK] - y[IKK])/tau[IKK] 
	dydt[JAK] = (OR(act(y[EGFR],w[58],n[58],EC50[58]),OR(act(y[ERBB],w[61],n[61],EC50[61]),OR(act(y[FGFR],w[66],n[66],EC50[66]),OR(act(y[FLT3],w[69],n[69],EC50[69]),OR(act(y[IGF1R],w[74],n[74],EC50[74]),OR(act(y[KIT],w[81],n[81],EC50[81]),OR(act(y[PDGFR],w[96],n[96],EC50[96]),act(y[VEGFR],w[109],n[109],EC50[109]))))))))*ymax[JAK] - y[JAK])/tau[JAK] 
	dydt[JNK] = (act(y[MEK47],w[86],n[86],EC50[86])*ymax[JNK] - y[JNK])/tau[JNK] 
	dydt[KIT] = (AND(w[33],[inhib(y[NIL],w[33],n[33],EC50[33]),inhib(y[PON],w[33],n[33],EC50[33]),act(y[SCF],w[33],n[33],EC50[33]),inhib(y[SOR],w[33],n[33],EC50[33]),inhib(y[SUN],w[33],n[33],EC50[33])])*ymax[KIT] - y[KIT])/tau[KIT] 
	dydt[MEK12] = (act(y[Raf],w[102],n[102],EC50[102])*ymax[MEK12] - y[MEK12])/tau[MEK12] 
	dydt[MEK36] = (act(y[ASK1],w[51],n[51],EC50[51])*ymax[MEK36] - y[MEK36])/tau[MEK36] 
	dydt[MEK47] = (act(y[ASK1],w[52],n[52],EC50[52])*ymax[MEK47] - y[MEK47])/tau[MEK47] 
	dydt[MOMP] = (act(y[Bax],w[53],n[53],EC50[53])*ymax[MOMP] - y[MOMP])/tau[MOMP] 
	dydt[NFkB] = (inhib(y[IkB],w[30],n[30],EC50[30])*ymax[NFkB] - y[NFkB])/tau[NFkB] 
	dydt[NIL] = (w[2]*ymax[NIL] - y[NIL])/tau[NIL] 
	dydt[NOX] = (OR(act(y[ERL],w[65],n[65],EC50[65]),act(y[NIL],w[90],n[90],EC50[90]))*ymax[NOX] - y[NOX])/tau[NOX] 
	dydt[Noxa] = (act(y[p53],w[94],n[94],EC50[94])*ymax[Noxa] - y[Noxa])/tau[Noxa] 
	dydt[NRG1] = (w[13]*ymax[NRG1] - y[NRG1])/tau[NRG1] 
	dydt[p38] = (act(y[MEK36],w[85],n[85],EC50[85])*ymax[p38] - y[p38])/tau[p38] 
	dydt[p53] = (act(y[AP1],w[49],n[49],EC50[49])*ymax[p53] - y[p53])/tau[p53] 
	dydt[PARP] = (inhib(y[cas3],w[26],n[26],EC50[26])*ymax[PARP] - y[PARP])/tau[PARP] 
	dydt[PDGF] = (w[14]*ymax[PDGF] - y[PDGF])/tau[PDGF] 
	dydt[PDGFR] = (AND(w[41],[act(y[PDGF],w[41],n[41],EC50[41]),inhib(y[SOR],w[41],n[41],EC50[41]),inhib(y[SUN],w[41],n[41],EC50[41])])*ymax[PDGFR] - y[PDGFR])/tau[PDGFR] 
	dydt[PDK1] = (act(y[PI3K],w[100],n[100],EC50[100])*ymax[PDK1] - y[PDK1])/tau[PDK1] 
	dydt[PI3K] = (OR(act(y[EGFR],w[59],n[59],EC50[59]),OR(act(y[ERBB],w[62],n[62],EC50[62]),OR(act(y[FGFR],w[67],n[67],EC50[67]),OR(act(y[FLT3],w[70],n[70],EC50[70]),OR(act(y[IGF1R],w[75],n[75],EC50[75]),OR(act(y[KIT],w[82],n[82],EC50[82]),OR(act(y[PDGFR],w[97],n[97],EC50[97]),act(y[VEGFR],w[110],n[110],EC50[110]))))))))*ymax[PI3K] - y[PI3K])/tau[PI3K] 
	dydt[PON] = (w[3]*ymax[PON] - y[PON])/tau[PON] 
	dydt[PUMA] = (act(y[p53],w[95],n[95],EC50[95])*ymax[PUMA] - y[PUMA])/tau[PUMA] 
	dydt[Raf] = (AND(w[43],[act(y[Ras],w[43],n[43],EC50[43]),inhib(y[SOR],w[43],n[43],EC50[43])])*ymax[Raf] - y[Raf])/tau[Raf] 
	dydt[Ras] = (OR(act(y[EGFR],w[60],n[60],EC50[60]),OR(act(y[ERBB],w[63],n[63],EC50[63]),OR(act(y[FGFR],w[68],n[68],EC50[68]),OR(act(y[FLT3],w[71],n[71],EC50[71]),OR(act(y[IGF1R],w[76],n[76],EC50[76]),OR(act(y[KIT],w[83],n[83],EC50[83]),OR(act(y[PDGFR],w[98],n[98],EC50[98]),act(y[VEGFR],w[111],n[111],EC50[111]))))))))*ymax[Ras] - y[Ras])/tau[Ras] 
	dydt[ROS] = (OR(w[15],OR(act(y[GEF],w[72],n[72],EC50[72]),OR(act(y[NOX],w[91],n[91],EC50[91]),OR(act(y[PON],w[101],n[101],EC50[101]),OR(act(y[SOR],w[105],n[105],EC50[105]),OR(act(y[SUN],w[107],n[107],EC50[107]),act(y[TRAZ],w[108],n[108],EC50[108])))))))*ymax[ROS] - y[ROS])/tau[ROS] 
	dydt[RSK] = (act(y[ERK12],w[64],n[64],EC50[64])*ymax[RSK] - y[RSK])/tau[RSK] 
	dydt[SCF] = (w[16]*ymax[SCF] - y[SCF])/tau[SCF] 
	dydt[Smac] = (act(y[MOMP],w[88],n[88],EC50[88])*ymax[Smac] - y[Smac])/tau[Smac] 
	dydt[SOR] = (w[4]*ymax[SOR] - y[SOR])/tau[SOR] 
	dydt[STAT] = (act(y[JAK],w[77],n[77],EC50[77])*ymax[STAT] - y[STAT])/tau[STAT] 
	dydt[SUN] = (w[5]*ymax[SUN] - y[SUN])/tau[SUN] 
	dydt[TRAZ] = (w[6]*ymax[TRAZ] - y[TRAZ])/tau[TRAZ] 
	dydt[Trx] = (AND(w[39],[inhib(y[ROS],w[39],n[39],EC50[39]),act(y[Trxt],w[39],n[39],EC50[39])])*ymax[Trx] - y[Trx])/tau[Trx] 
	dydt[Trxt] = (w[17]*ymax[Trxt] - y[Trxt])/tau[Trxt] 
	dydt[VEGF] = (w[18]*ymax[VEGF] - y[VEGF])/tau[VEGF] 
	dydt[VEGFR] = (AND(w[42],[inhib(y[SOR],w[42],n[42],EC50[42]),inhib(y[SUN],w[42],n[42],EC50[42]),act(y[VEGF],w[42],n[42],EC50[42])])*ymax[VEGFR] - y[VEGFR])/tau[VEGFR] 
	dydt[xIAP] = (AND(w[40],[inhib(y[Smac],w[40],n[40],EC50[40]),act(y[xIAPt],w[40],n[40],EC50[40])])*ymax[xIAP] - y[xIAP])/tau[xIAP] 
	dydt[xIAPt] = (w[19]*ymax[xIAPt] - y[xIAPt])/tau[xIAPt] 
	return dydt 

# utility functions
 
def act(x, w, n, EC50): 
	# hill activation function with parameters w (weight), n (Hill coeff), EC50 
	beta = ((EC50**n)-1)/(2*EC50**n-1) 
	K = (beta-1)**(1/n) 
	fact = w*(beta*x**n)/(K**n+x**n) 
	if fact > w: 
		fact = w 
	return fact
 
def inhib(x, w, n, EC50): 
	# inverse hill function with parameters w (weight), n (Hill coeff), EC50 
	finhib = w - act(x, w, n, EC50) 
	return finhib
 
def OR(x, y): 
	# OR logic gate 
	z = x + y - x*y 
	return z
 
def AND(w, reactList): 
	# AND logic gate, multiplying all of the reactants together 
	if w == 0: 
		z = 0 
	else: 
		p = np.array(reactList).prod() 
		z = p/w**(len(reactList)-2) 
	return z
 
