# LRP1_upstream.py 
# Automatically generated by Netflux on 26-Feb-2024 
import numpy as np 
def ODEfunc(t,y,tau,ymax,w,n,EC50): 
	Akt = 0 
	AP1 = 1 
	apoptosis = 2 
	ASK1 = 3 
	Bad = 4 
	Bax = 5 
	Bcl2 = 6 
	Bcl2t = 7 
	Bim = 8 
	CAD = 9 
	cas3 = 10 
	cas9 = 11 
	cellDeath = 12 
	CREB = 13 
	cytc = 14 
	DNAfrag = 15 
	EGF = 16 
	EGFR = 17 
	ERBB = 18 
	ERK12 = 19 
	FGF = 20 
	FGFR = 21 
	FLT3 = 22 
	FLT3L = 23 
	iCAD = 24 
	iCADt = 25 
	IGF1 = 26 
	IGF1R = 27 
	IkB = 28 
	IKK = 29 
	JAK = 30 
	JNK = 31 
	KIT = 32 
	LRP1 = 33 
	LRP1ag = 34 
	MEK12 = 35 
	MEK36 = 36 
	MEK47 = 37 
	MOMP = 38 
	NFkB = 39 
	NOX = 40 
	Noxa = 41 
	NRG1 = 42 
	p38 = 43 
	p53 = 44 
	PARP = 45 
	PDGF = 46 
	PDGFR = 47 
	PDK1 = 48 
	PI3K = 49 
	PKC = 50 
	PUMA = 51 
	Raf = 52 
	Ras = 53 
	ROS = 54 
	RSK = 55 
	SCF = 56 
	Shc1 = 57 
	Shp2 = 58 
	Smac = 59 
	Src = 60 
	STAT = 61 
	Trx = 62 
	Trxt = 63 
	VEGF = 64 
	VEGFR = 65 
	xIAP = 66 
	xIAPt = 67 
	dydt = np.zeros(68) 
	dydt[Akt] = (act(y[PDK1],w[90],n[90],EC50[90])*ymax[Akt] - y[Akt])/tau[Akt] 
	dydt[AP1] = (act(y[JNK],w[70],n[70],EC50[70])*ymax[AP1] - y[AP1])/tau[AP1] 
	dydt[apoptosis] = (act(y[DNAfrag],w[51],n[51],EC50[51])*ymax[apoptosis] - y[apoptosis])/tau[apoptosis] 
	dydt[ASK1] = (OR(inhib(y[Trx],w[39],n[39],EC50[39]),AND(w[93],[inhib(y[Akt],w[93],n[93],EC50[93]),act(y[ROS],w[93],n[93],EC50[93])]))*ymax[ASK1] - y[ASK1])/tau[ASK1] 
	dydt[Bad] = (OR(inhib(y[Akt],w[15],n[15],EC50[15]),act(y[JNK],w[71],n[71],EC50[71]))*ymax[Bad] - y[Bad])/tau[Bad] 
	dydt[Bax] = (OR(AND(w[14],[inhib(y[Akt],w[14],n[14],EC50[14]),act(y[ROS],w[14],n[14],EC50[14])]),OR(inhib(y[Bcl2],w[18],n[18],EC50[18]),act(y[p53],w[84],n[84],EC50[84])))*ymax[Bax] - y[Bax])/tau[Bax] 
	dydt[Bcl2] = (OR(AND(w[17],[inhib(y[Bad],w[17],n[17],EC50[17]),act(y[Bcl2t],w[17],n[17],EC50[17])]),OR(AND(w[19],[act(y[Bcl2t],w[19],n[19],EC50[19]),inhib(y[Bim],w[19],n[19],EC50[19])]),OR(AND(w[26],[act(y[Bcl2t],w[26],n[26],EC50[26]),inhib(y[JNK],w[26],n[26],EC50[26])]),OR(AND(w[28],[act(y[Bcl2t],w[28],n[28],EC50[28]),inhib(y[Noxa],w[28],n[28],EC50[28])]),AND(w[32],[act(y[Bcl2t],w[32],n[32],EC50[32]),inhib(y[PUMA],w[32],n[32],EC50[32])])))))*ymax[Bcl2] - y[Bcl2])/tau[Bcl2] 
	dydt[Bcl2t] = (OR(w[1],OR(act(y[CREB],w[49],n[49],EC50[49]),OR(act(y[NFkB],w[81],n[81],EC50[81]),act(y[STAT],w[95],n[95],EC50[95]))))*ymax[Bcl2t] - y[Bcl2t])/tau[Bcl2t] 
	dydt[Bim] = (OR(inhib(y[Akt],w[16],n[16],EC50[16]),OR(act(y[JNK],w[72],n[72],EC50[72]),act(y[p38],w[83],n[83],EC50[83])))*ymax[Bim] - y[Bim])/tau[Bim] 
	dydt[CAD] = (inhib(y[iCAD],w[23],n[23],EC50[23])*ymax[CAD] - y[CAD])/tau[CAD] 
	dydt[cas3] = (OR(inhib(y[xIAP],w[40],n[40],EC50[40]),act(y[cas9],w[48],n[48],EC50[48]))*ymax[cas3] - y[cas3])/tau[cas3] 
	dydt[cas9] = (OR(inhib(y[xIAP],w[41],n[41],EC50[41]),act(y[cytc],w[50],n[50],EC50[50]))*ymax[cas9] - y[cas9])/tau[cas9] 
	dydt[cellDeath] = (act(y[apoptosis],w[44],n[44],EC50[44])*ymax[cellDeath] - y[cellDeath])/tau[cellDeath] 
	dydt[CREB] = (act(y[RSK],w[94],n[94],EC50[94])*ymax[CREB] - y[CREB])/tau[CREB] 
	dydt[cytc] = (act(y[MOMP],w[79],n[79],EC50[79])*ymax[cytc] - y[cytc])/tau[cytc] 
	dydt[DNAfrag] = (AND(w[29],[act(y[CAD],w[29],n[29],EC50[29]),inhib(y[PARP],w[29],n[29],EC50[29])])*ymax[DNAfrag] - y[DNAfrag])/tau[DNAfrag] 
	dydt[EGF] = (w[2]*ymax[EGF] - y[EGF])/tau[EGF] 
	dydt[EGFR] = (act(y[EGF],w[22],n[22],EC50[22])*ymax[EGFR] - y[EGFR])/tau[EGFR] 
	dydt[ERBB] = (act(y[NRG1],w[38],n[38],EC50[38])*ymax[ERBB] - y[ERBB])/tau[ERBB] 
	dydt[ERK12] = (act(y[MEK12],w[76],n[76],EC50[76])*ymax[ERK12] - y[ERK12])/tau[ERK12] 
	dydt[FGF] = (w[3]*ymax[FGF] - y[FGF])/tau[FGF] 
	dydt[FGFR] = (act(y[FGF],w[31],n[31],EC50[31])*ymax[FGFR] - y[FGFR])/tau[FGFR] 
	dydt[FLT3] = (act(y[FLT3L],w[30],n[30],EC50[30])*ymax[FLT3] - y[FLT3])/tau[FLT3] 
	dydt[FLT3L] = (w[4]*ymax[FLT3L] - y[FLT3L])/tau[FLT3L] 
	dydt[iCAD] = (AND(w[21],[inhib(y[cas3],w[21],n[21],EC50[21]),act(y[iCADt],w[21],n[21],EC50[21])])*ymax[iCAD] - y[iCAD])/tau[iCAD] 
	dydt[iCADt] = (w[5]*ymax[iCADt] - y[iCADt])/tau[iCADt] 
	dydt[IGF1] = (w[6]*ymax[IGF1] - y[IGF1])/tau[IGF1] 
	dydt[IGF1R] = (act(y[IGF1],w[65],n[65],EC50[65])*ymax[IGF1R] - y[IGF1R])/tau[IGF1R] 
	dydt[IkB] = (inhib(y[IKK],w[25],n[25],EC50[25])*ymax[IkB] - y[IkB])/tau[IkB] 
	dydt[IKK] = (act(y[Akt],w[42],n[42],EC50[42])*ymax[IKK] - y[IKK])/tau[IKK] 
	dydt[JAK] = (OR(act(y[EGFR],w[52],n[52],EC50[52]),OR(act(y[ERBB],w[55],n[55],EC50[55]),OR(act(y[FGFR],w[59],n[59],EC50[59]),OR(act(y[FLT3],w[62],n[62],EC50[62]),OR(act(y[IGF1R],w[66],n[66],EC50[66]),OR(act(y[KIT],w[73],n[73],EC50[73]),OR(act(y[PDGFR],w[87],n[87],EC50[87]),act(y[VEGFR],w[96],n[96],EC50[96]))))))))*ymax[JAK] - y[JAK])/tau[JAK] 
	dydt[JNK] = (act(y[MEK47],w[78],n[78],EC50[78])*ymax[JNK] - y[JNK])/tau[JNK] 
	dydt[KIT] = (act(y[SCF],w[27],n[27],EC50[27])*ymax[KIT] - y[KIT])/tau[KIT] 
	dydt[LRP1] = (act(y[LRP1ag],w[99],n[99],EC50[99])*ymax[LRP1] - y[LRP1])/tau[LRP1] 
	dydt[LRP1ag] = (w[0]*ymax[LRP1ag] - y[LRP1ag])/tau[LRP1ag] 
	dydt[MEK12] = (act(y[Raf],w[92],n[92],EC50[92])*ymax[MEK12] - y[MEK12])/tau[MEK12] 
	dydt[MEK36] = (act(y[ASK1],w[45],n[45],EC50[45])*ymax[MEK36] - y[MEK36])/tau[MEK36] 
	dydt[MEK47] = (act(y[ASK1],w[46],n[46],EC50[46])*ymax[MEK47] - y[MEK47])/tau[MEK47] 
	dydt[MOMP] = (act(y[Bax],w[47],n[47],EC50[47])*ymax[MOMP] - y[MOMP])/tau[MOMP] 
	dydt[NFkB] = (inhib(y[IkB],w[24],n[24],EC50[24])*ymax[NFkB] - y[NFkB])/tau[NFkB] 
	dydt[NOX] = (0*ymax[NOX] - y[NOX])/tau[NOX] 
	dydt[Noxa] = (act(y[p53],w[85],n[85],EC50[85])*ymax[Noxa] - y[Noxa])/tau[Noxa] 
	dydt[NRG1] = (w[7]*ymax[NRG1] - y[NRG1])/tau[NRG1] 
	dydt[p38] = (act(y[MEK36],w[77],n[77],EC50[77])*ymax[p38] - y[p38])/tau[p38] 
	dydt[p53] = (act(y[AP1],w[43],n[43],EC50[43])*ymax[p53] - y[p53])/tau[p53] 
	dydt[PARP] = (inhib(y[cas3],w[20],n[20],EC50[20])*ymax[PARP] - y[PARP])/tau[PARP] 
	dydt[PDGF] = (w[8]*ymax[PDGF] - y[PDGF])/tau[PDGF] 
	dydt[PDGFR] = (OR(act(y[PDGF],w[35],n[35],EC50[35]),AND(w[104],[act(y[PDGF],w[104],n[104],EC50[104]),inhib(y[Shp2],w[104],n[104],EC50[104])]))*ymax[PDGFR] - y[PDGFR])/tau[PDGFR] 
	dydt[PDK1] = (act(y[PI3K],w[91],n[91],EC50[91])*ymax[PDK1] - y[PDK1])/tau[PDK1] 
	dydt[PI3K] = (OR(act(y[EGFR],w[53],n[53],EC50[53]),OR(act(y[ERBB],w[56],n[56],EC50[56]),OR(act(y[FGFR],w[60],n[60],EC50[60]),OR(act(y[FLT3],w[63],n[63],EC50[63]),OR(act(y[IGF1R],w[67],n[67],EC50[67]),OR(act(y[KIT],w[74],n[74],EC50[74]),OR(act(y[PDGFR],w[88],n[88],EC50[88]),OR(act(y[VEGFR],w[97],n[97],EC50[97]),OR(act(y[LRP1],w[100],n[100],EC50[100]),act(y[Src],w[108],n[108],EC50[108]))))))))))*ymax[PI3K] - y[PI3K])/tau[PI3K] 
	dydt[PKC] = (act(y[LRP1],w[102],n[102],EC50[102])*ymax[PKC] - y[PKC])/tau[PKC] 
	dydt[PUMA] = (act(y[p53],w[86],n[86],EC50[86])*ymax[PUMA] - y[PUMA])/tau[PUMA] 
	dydt[Raf] = (act(y[Ras],w[37],n[37],EC50[37])*ymax[Raf] - y[Raf])/tau[Raf] 
	dydt[Ras] = (OR(act(y[EGFR],w[54],n[54],EC50[54]),OR(act(y[ERBB],w[57],n[57],EC50[57]),OR(act(y[FGFR],w[61],n[61],EC50[61]),OR(act(y[FLT3],w[64],n[64],EC50[64]),OR(act(y[IGF1R],w[68],n[68],EC50[68]),OR(act(y[KIT],w[75],n[75],EC50[75]),OR(act(y[PDGFR],w[89],n[89],EC50[89]),OR(act(y[VEGFR],w[98],n[98],EC50[98]),OR(act(y[LRP1],w[101],n[101],EC50[101]),act(y[Src],w[107],n[107],EC50[107]))))))))))*ymax[Ras] - y[Ras])/tau[Ras] 
	dydt[ROS] = (OR(w[9],act(y[NOX],w[82],n[82],EC50[82]))*ymax[ROS] - y[ROS])/tau[ROS] 
	dydt[RSK] = (act(y[ERK12],w[58],n[58],EC50[58])*ymax[RSK] - y[RSK])/tau[RSK] 
	dydt[SCF] = (w[10]*ymax[SCF] - y[SCF])/tau[SCF] 
	dydt[Shc1] = (act(y[PKC],w[105],n[105],EC50[105])*ymax[Shc1] - y[Shc1])/tau[Shc1] 
	dydt[Shp2] = (act(y[LRP1],w[103],n[103],EC50[103])*ymax[Shp2] - y[Shp2])/tau[Shp2] 
	dydt[Smac] = (act(y[MOMP],w[80],n[80],EC50[80])*ymax[Smac] - y[Smac])/tau[Smac] 
	dydt[Src] = (OR(act(y[Shp2],w[106],n[106],EC50[106]),OR(act(y[PDGFR],w[109],n[109],EC50[109]),act(y[Shc1],w[110],n[110],EC50[110])))*ymax[Src] - y[Src])/tau[Src] 
	dydt[STAT] = (act(y[JAK],w[69],n[69],EC50[69])*ymax[STAT] - y[STAT])/tau[STAT] 
	dydt[Trx] = (AND(w[33],[inhib(y[ROS],w[33],n[33],EC50[33]),act(y[Trxt],w[33],n[33],EC50[33])])*ymax[Trx] - y[Trx])/tau[Trx] 
	dydt[Trxt] = (w[11]*ymax[Trxt] - y[Trxt])/tau[Trxt] 
	dydt[VEGF] = (w[12]*ymax[VEGF] - y[VEGF])/tau[VEGF] 
	dydt[VEGFR] = (act(y[VEGF],w[36],n[36],EC50[36])*ymax[VEGFR] - y[VEGFR])/tau[VEGFR] 
	dydt[xIAP] = (AND(w[34],[inhib(y[Smac],w[34],n[34],EC50[34]),act(y[xIAPt],w[34],n[34],EC50[34])])*ymax[xIAP] - y[xIAP])/tau[xIAP] 
	dydt[xIAPt] = (w[13]*ymax[xIAPt] - y[xIAPt])/tau[xIAPt] 
	return dydt 

# utility functions
 
def act(x, w, n, EC50): 
	# hill activation function with parameters w (weight), n (Hill coeff), EC50 
	beta = ((EC50**n)-1)/(2*EC50**n-1) 
	K = (beta-1)**(1/n) 
	fact = w*(beta*x**n)/(K**n+x**n) 
	if fact > w: 
		fact = w 
	return fact
 
def inhib(x, w, n, EC50): 
	# inverse hill function with parameters w (weight), n (Hill coeff), EC50 
	finhib = w - act(x, w, n, EC50) 
	return finhib
 
def OR(x, y): 
	# OR logic gate 
	z = x + y - x*y 
	return z
 
def AND(w, reactList): 
	# AND logic gate, multiplying all of the reactants together 
	if w == 0: 
		z = 0 
	else: 
		p = np.array(reactList).prod() 
		z = p/w**(len(reactList)-2) 
	return z
 
