function dydt=ODEfun(t,y,params) 
% ODEfun.m 
% Automatically generated by Netflux on 27-Feb-2024
 
% Assign names for parameters 
[rpar,tau,ymax,speciesNames]=params{:}; 
Akt = 1; 
AP1 = 2; 
apoptosis = 3; 
ASK1 = 4; 
Bad = 5; 
Bax = 6; 
Bcl2 = 7; 
Bcl2t = 8; 
Bim = 9; 
CAD = 10; 
cas3 = 11; 
cas9 = 12; 
cellDeath = 13; 
CREB = 14; 
cytc = 15; 
DNAfrag = 16; 
EGF = 17; 
EGFR = 18; 
ERBB = 19; 
ERK12 = 20; 
FGF = 21; 
FGFR = 22; 
FLT3 = 23; 
FLT3L = 24; 
iCAD = 25; 
iCADt = 26; 
IGF1 = 27; 
IGF1R = 28; 
IkB = 29; 
IKK = 30; 
JAK = 31; 
JNK = 32; 
KIT = 33; 
LRP1 = 34; 
LRP1ag = 35; 
MEK12 = 36; 
MEK36 = 37; 
MEK47 = 38; 
MOMP = 39; 
NFkB = 40; 
NOX = 41; 
Noxa = 42; 
NRG1 = 43; 
p38 = 44; 
p53 = 45; 
PARP = 46; 
PDGF = 47; 
PDGFR = 48; 
PDK1 = 49; 
PI3K = 50; 
PKC = 51; 
PUMA = 52; 
Raf = 53; 
Ras = 54; 
ROS = 55; 
RSK = 56; 
SCF = 57; 
Shc1 = 58; 
Shp2 = 59; 
Smac = 60; 
Src = 61; 
STAT = 62; 
Trx = 63; 
Trxt = 64; 
VEGF = 65; 
VEGFR = 66; 
xIAP = 67; 
xIAPt = 68; 
dydt = zeros(68,1); 
dydt(Akt) = (act(y(PDK1),rpar(:,91))*ymax(Akt) - y(Akt))/tau(Akt); 
dydt(AP1) = (act(y(JNK),rpar(:,71))*ymax(AP1) - y(AP1))/tau(AP1); 
dydt(apoptosis) = (act(y(DNAfrag),rpar(:,52))*ymax(apoptosis) - y(apoptosis))/tau(apoptosis); 
dydt(ASK1) = (OR(inhib(y(Trx),rpar(:,40)),AND(rpar(:,94),inhib(y(Akt),rpar(:,94)),act(y(ROS),rpar(:,94))))*ymax(ASK1) - y(ASK1))/tau(ASK1); 
dydt(Bad) = (OR(inhib(y(Akt),rpar(:,16)),act(y(JNK),rpar(:,72)))*ymax(Bad) - y(Bad))/tau(Bad); 
dydt(Bax) = (OR(AND(rpar(:,15),inhib(y(Akt),rpar(:,15)),act(y(ROS),rpar(:,15))),OR(inhib(y(Bcl2),rpar(:,19)),act(y(p53),rpar(:,85))))*ymax(Bax) - y(Bax))/tau(Bax); 
dydt(Bcl2) = (OR(AND(rpar(:,18),inhib(y(Bad),rpar(:,18)),act(y(Bcl2t),rpar(:,18))),OR(AND(rpar(:,20),act(y(Bcl2t),rpar(:,20)),inhib(y(Bim),rpar(:,20))),OR(AND(rpar(:,27),act(y(Bcl2t),rpar(:,27)),inhib(y(JNK),rpar(:,27))),OR(AND(rpar(:,29),act(y(Bcl2t),rpar(:,29)),inhib(y(Noxa),rpar(:,29))),AND(rpar(:,33),act(y(Bcl2t),rpar(:,33)),inhib(y(PUMA),rpar(:,33)))))))*ymax(Bcl2) - y(Bcl2))/tau(Bcl2); 
dydt(Bcl2t) = (OR(rpar(1,2),OR(act(y(CREB),rpar(:,50)),OR(act(y(NFkB),rpar(:,82)),act(y(STAT),rpar(:,96)))))*ymax(Bcl2t) - y(Bcl2t))/tau(Bcl2t); 
dydt(Bim) = (OR(inhib(y(Akt),rpar(:,17)),OR(act(y(JNK),rpar(:,73)),act(y(p38),rpar(:,84))))*ymax(Bim) - y(Bim))/tau(Bim); 
dydt(CAD) = (inhib(y(iCAD),rpar(:,24))*ymax(CAD) - y(CAD))/tau(CAD); 
dydt(cas3) = (OR(inhib(y(xIAP),rpar(:,41)),act(y(cas9),rpar(:,49)))*ymax(cas3) - y(cas3))/tau(cas3); 
dydt(cas9) = (OR(inhib(y(xIAP),rpar(:,42)),act(y(cytc),rpar(:,51)))*ymax(cas9) - y(cas9))/tau(cas9); 
dydt(cellDeath) = (act(y(apoptosis),rpar(:,45))*ymax(cellDeath) - y(cellDeath))/tau(cellDeath); 
dydt(CREB) = (act(y(RSK),rpar(:,95))*ymax(CREB) - y(CREB))/tau(CREB); 
dydt(cytc) = (act(y(MOMP),rpar(:,80))*ymax(cytc) - y(cytc))/tau(cytc); 
dydt(DNAfrag) = (AND(rpar(:,30),act(y(CAD),rpar(:,30)),inhib(y(PARP),rpar(:,30)))*ymax(DNAfrag) - y(DNAfrag))/tau(DNAfrag); 
dydt(EGF) = (rpar(1,3)*ymax(EGF) - y(EGF))/tau(EGF); 
dydt(EGFR) = (act(y(EGF),rpar(:,23))*ymax(EGFR) - y(EGFR))/tau(EGFR); 
dydt(ERBB) = (act(y(NRG1),rpar(:,39))*ymax(ERBB) - y(ERBB))/tau(ERBB); 
dydt(ERK12) = (act(y(MEK12),rpar(:,77))*ymax(ERK12) - y(ERK12))/tau(ERK12); 
dydt(FGF) = (rpar(1,4)*ymax(FGF) - y(FGF))/tau(FGF); 
dydt(FGFR) = (act(y(FGF),rpar(:,32))*ymax(FGFR) - y(FGFR))/tau(FGFR); 
dydt(FLT3) = (act(y(FLT3L),rpar(:,31))*ymax(FLT3) - y(FLT3))/tau(FLT3); 
dydt(FLT3L) = (rpar(1,5)*ymax(FLT3L) - y(FLT3L))/tau(FLT3L); 
dydt(iCAD) = (AND(rpar(:,22),inhib(y(cas3),rpar(:,22)),act(y(iCADt),rpar(:,22)))*ymax(iCAD) - y(iCAD))/tau(iCAD); 
dydt(iCADt) = (rpar(1,6)*ymax(iCADt) - y(iCADt))/tau(iCADt); 
dydt(IGF1) = (rpar(1,7)*ymax(IGF1) - y(IGF1))/tau(IGF1); 
dydt(IGF1R) = (act(y(IGF1),rpar(:,66))*ymax(IGF1R) - y(IGF1R))/tau(IGF1R); 
dydt(IkB) = (inhib(y(IKK),rpar(:,26))*ymax(IkB) - y(IkB))/tau(IkB); 
dydt(IKK) = (act(y(Akt),rpar(:,43))*ymax(IKK) - y(IKK))/tau(IKK); 
dydt(JAK) = (OR(act(y(EGFR),rpar(:,53)),OR(act(y(ERBB),rpar(:,56)),OR(act(y(FGFR),rpar(:,60)),OR(act(y(FLT3),rpar(:,63)),OR(act(y(IGF1R),rpar(:,67)),OR(act(y(KIT),rpar(:,74)),OR(act(y(PDGFR),rpar(:,88)),act(y(VEGFR),rpar(:,97)))))))))*ymax(JAK) - y(JAK))/tau(JAK); 
dydt(JNK) = (act(y(MEK47),rpar(:,79))*ymax(JNK) - y(JNK))/tau(JNK); 
dydt(KIT) = (act(y(SCF),rpar(:,28))*ymax(KIT) - y(KIT))/tau(KIT); 
dydt(LRP1) = (act(y(LRP1ag),rpar(:,100))*ymax(LRP1) - y(LRP1))/tau(LRP1); 
dydt(LRP1ag) = (rpar(1,1)*ymax(LRP1ag) - y(LRP1ag))/tau(LRP1ag); 
dydt(MEK12) = (act(y(Raf),rpar(:,93))*ymax(MEK12) - y(MEK12))/tau(MEK12); 
dydt(MEK36) = (act(y(ASK1),rpar(:,46))*ymax(MEK36) - y(MEK36))/tau(MEK36); 
dydt(MEK47) = (act(y(ASK1),rpar(:,47))*ymax(MEK47) - y(MEK47))/tau(MEK47); 
dydt(MOMP) = (act(y(Bax),rpar(:,48))*ymax(MOMP) - y(MOMP))/tau(MOMP); 
dydt(NFkB) = (inhib(y(IkB),rpar(:,25))*ymax(NFkB) - y(NFkB))/tau(NFkB); 
dydt(NOX) = (0*ymax(NOX) - y(NOX))/tau(NOX); 
dydt(Noxa) = (act(y(p53),rpar(:,86))*ymax(Noxa) - y(Noxa))/tau(Noxa); 
dydt(NRG1) = (rpar(1,8)*ymax(NRG1) - y(NRG1))/tau(NRG1); 
dydt(p38) = (act(y(MEK36),rpar(:,78))*ymax(p38) - y(p38))/tau(p38); 
dydt(p53) = (act(y(AP1),rpar(:,44))*ymax(p53) - y(p53))/tau(p53); 
dydt(PARP) = (inhib(y(cas3),rpar(:,21))*ymax(PARP) - y(PARP))/tau(PARP); 
dydt(PDGF) = (rpar(1,9)*ymax(PDGF) - y(PDGF))/tau(PDGF); 
dydt(PDGFR) = (OR(act(y(PDGF),rpar(:,36)),AND(rpar(:,105),act(y(PDGF),rpar(:,105)),inhib(y(Shp2),rpar(:,105))))*ymax(PDGFR) - y(PDGFR))/tau(PDGFR); 
dydt(PDK1) = (act(y(PI3K),rpar(:,92))*ymax(PDK1) - y(PDK1))/tau(PDK1); 
dydt(PI3K) = (OR(act(y(EGFR),rpar(:,54)),OR(act(y(ERBB),rpar(:,57)),OR(act(y(FGFR),rpar(:,61)),OR(act(y(FLT3),rpar(:,64)),OR(act(y(IGF1R),rpar(:,68)),OR(act(y(KIT),rpar(:,75)),OR(act(y(PDGFR),rpar(:,89)),OR(act(y(VEGFR),rpar(:,98)),OR(act(y(LRP1),rpar(:,101)),act(y(Src),rpar(:,109)))))))))))*ymax(PI3K) - y(PI3K))/tau(PI3K); 
dydt(PKC) = (act(y(LRP1),rpar(:,103))*ymax(PKC) - y(PKC))/tau(PKC); 
dydt(PUMA) = (act(y(p53),rpar(:,87))*ymax(PUMA) - y(PUMA))/tau(PUMA); 
dydt(Raf) = (act(y(Ras),rpar(:,38))*ymax(Raf) - y(Raf))/tau(Raf); 
dydt(Ras) = (OR(act(y(EGFR),rpar(:,55)),OR(act(y(ERBB),rpar(:,58)),OR(act(y(FGFR),rpar(:,62)),OR(act(y(FLT3),rpar(:,65)),OR(act(y(IGF1R),rpar(:,69)),OR(act(y(KIT),rpar(:,76)),OR(act(y(PDGFR),rpar(:,90)),OR(act(y(VEGFR),rpar(:,99)),OR(act(y(LRP1),rpar(:,102)),act(y(Src),rpar(:,108)))))))))))*ymax(Ras) - y(Ras))/tau(Ras); 
dydt(ROS) = (OR(rpar(1,10),act(y(NOX),rpar(:,83)))*ymax(ROS) - y(ROS))/tau(ROS); 
dydt(RSK) = (act(y(ERK12),rpar(:,59))*ymax(RSK) - y(RSK))/tau(RSK); 
dydt(SCF) = (rpar(1,11)*ymax(SCF) - y(SCF))/tau(SCF); 
dydt(Shc1) = (act(y(PKC),rpar(:,106))*ymax(Shc1) - y(Shc1))/tau(Shc1); 
dydt(Shp2) = (act(y(LRP1),rpar(:,104))*ymax(Shp2) - y(Shp2))/tau(Shp2); 
dydt(Smac) = (act(y(MOMP),rpar(:,81))*ymax(Smac) - y(Smac))/tau(Smac); 
dydt(Src) = (OR(act(y(Shp2),rpar(:,107)),OR(act(y(PDGFR),rpar(:,110)),act(y(Shc1),rpar(:,111))))*ymax(Src) - y(Src))/tau(Src); 
dydt(STAT) = (act(y(JAK),rpar(:,70))*ymax(STAT) - y(STAT))/tau(STAT); 
dydt(Trx) = (AND(rpar(:,34),inhib(y(ROS),rpar(:,34)),act(y(Trxt),rpar(:,34)))*ymax(Trx) - y(Trx))/tau(Trx); 
dydt(Trxt) = (rpar(1,12)*ymax(Trxt) - y(Trxt))/tau(Trxt); 
dydt(VEGF) = (rpar(1,13)*ymax(VEGF) - y(VEGF))/tau(VEGF); 
dydt(VEGFR) = (act(y(VEGF),rpar(:,37))*ymax(VEGFR) - y(VEGFR))/tau(VEGFR); 
dydt(xIAP) = (AND(rpar(:,35),inhib(y(Smac),rpar(:,35)),act(y(xIAPt),rpar(:,35)))*ymax(xIAP) - y(xIAP))/tau(xIAP); 
dydt(xIAPt) = (rpar(1,14)*ymax(xIAPt) - y(xIAPt))/tau(xIAPt); 

% utility functions 
function fact = act(x,rpar) 
% hill activation function with parameters w (weight), n (Hill coeff), EC50 
    w = rpar(1); 
    n = rpar(2); 
    EC50 = rpar(3); 
    beta = (EC50.^n - 1)./(2*EC50.^n - 1); 
    K = (beta - 1).^(1./n); 
    fact = w.*(beta.*x.^n)./(K.^n + x.^n); 
    if fact>w,                 % cap fact(x)<= 1 
        fact = w; 
    end
 
function finhib = inhib(x,rpar) 
% inverse hill function with parameters w (weight), n (Hill coeff), EC50 
    finhib = rpar(1) - act(x,rpar);
 
function z = OR(x,y) 
% OR logic gate 
    z = x + y - x*y;
 
function z = AND(rpar,varargin) 
% AND logic gate, multiplying all of the reactants together 
    w = rpar(1); 
    if w == 0, 
        z = 0; 
    else 
        v = cell2mat(varargin); 
        z = prod(v)/w^(nargin-2);  
    end 
